[REVERTME] manifest: Sync grpc-grpc from AOSP.
Revert this when CLO mirrors fix this issue.

Remove it from system.xml as well because repo syncs
system.xml before aosp.xml which gives an error :

fatal: bad object 5ac5bce291b4beab83f692302aff16198185bb0d
error: https://git.codelinaro.org/clo/la/platform/external/grpc-grpc did not send all necessary objects
error: Cannot fetch platform/external/grpc-grpc from https://git.codelinaro.org/clo/la/platform/external/grpc-grpc
Change-Id: I8fbc702242db1e9a23002e6bc276334f3ea82c6d