manifest: Fork packages/modules/common
AOSP added new modules and QC has some of their own
for Wi-Fi also.

Fixes
FAILED: Diff packages/modules/common/build/allowed_deps.txt and /out/jake/soong/apex/depsinfo/new-allowed-deps.txt
Outputs: /out/jake/soong/apex/depsinfo/new-allowed-deps.txt.check
Error: exited with code: 1
Command:                        if grep -v '^#' packages/modules/common/build/allowed_deps.txt | diff -B - /out/jake/soong/apex/depsinfo/new-allowed-deps.txt; then
  touch /out/jake/soong/apex/depsinfo/new-allowed-deps.txt.check;                       else                            echo -e "\n******************************";          echo "ERROR: go/apex-allowed-deps-error";                                echo "******************************";                          echo "Detected changes to allowed dependencies in updatable modules.";                                echo "To fix and update packages/modules/common/build/allowed_deps.txt, please run:";                        echo -e "$ (croot && packages/modules/common/build/update-apex-allowed-deps.sh)\n";                              echo "When submitting the generated CL, you must include the following information";                          echo "in the commit message if you are adding a new dependency:";                               echo "Apex-Size-Increase:";  echo "Previous-Platform-Support:";                               echo "Aosp-First:";                             echo "Test-Info:";                              echo "You do not need OWNERS approval to submit the change, but mainline-modularization@";                            echo "will periodically review additions and may require changes.";  echo -e "******************************\n";                              exit 1;                 fi;
Output:
954a955
> prebuilt_car-ui-lib-source(minSdkVersion:28)
-e
******************************
ERROR: go/apex-allowed-deps-error
******************************
Detected changes to allowed dependencies in updatable modules.
To fix and update packages/modules/common/build/allowed_deps.txt, please run:
-e $ (croot && packages/modules/common/build/update-apex-allowed-deps.sh)

When submitting the generated CL, you must include the following information
in the commit message if you are adding a new dependency:
Apex-Size-Increase:
Previous-Platform-Support:
Aosp-First:
Test-Info:
You do not need OWNERS approval to submit the change, but mainline-modularization@
will periodically review additions and may require changes.
-e ******************************

Change-Id: Ia6246355dcd7c0fd349d42986f3c2a326d4211af