manifest: Remove Car repos for now
Because of Qualcomm's Bluetooth modules changes
(mostly using a really old version), AOSP Car
gives the error below. Track from CLO.

error: packages/services/Car/car-lib-module/Android.bp:22:1: module "android.car-module.stubs.source.module_lib" variant "android_common" (created by module "android.car-module" variant "android_common"): source path "packages/modules/Bluetooth/framework/aidl-export" does not exist

Change-Id: I577216125abd15af74f147128251cf4ee23eb367